# Generated by Django 6.1 on 2026-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='days_admitted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='diagnosis_procedure_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='duplicate_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='hospital_claim_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_claim_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='previous_claim_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='claim',
            name='previous_claims',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='claim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
