# Generated by Django 6.1 on 2026-08-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_admission_date_claim_claim_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_type', models.CharField(choices=[('none', 'None'), ('duplicate', 'Duplicate Claim'), ('inflated_amount', 'Inflated Amount'), ('suspicious_provider', 'Suspicious Provider'), ('excessive_claims', 'Excessive Claims'), ('diagnosis_mismatch', 'Diagnosis/Procedure Mismatch')], default='none', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_label', to='claims.claim')),
            ],
        ),
    ]
