# Generated by Django 6.1 on 2026-08-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0005_fraudlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('fraud_detected', models.BooleanField(default=False)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_analysis', to='claims.claim')),
            ],
        ),
    ]
