# Generated by Django 6.1 on 2026-08-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudanalysis',
            name='ml_confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fraudanalysis',
            name='recommended_action',
            field=models.CharField(choices=[('approve', 'Auto-Approve'), ('review', 'Manual Review Required'), ('reject', 'Auto-Reject')], default='approve', max_length=20),
        ),
        migrations.AddField(
            model_name='fraudanalysis',
            name='rule_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
